Add MLContextMLogregTest
j143/systemds pull request #33
Opened 2020-10-18 15:53 UTC by omkarghugarkar007

1. Tried out by removing the comments of the Lines and made changes to the code.
2. Currently getting the following error 
![image](https://user-images.githubusercontent.com/62425457/96373136-1cb85900-1188-11eb-8732-d6790725bba4.png)
3. Debugging the code to get rid of the error.

2020-10-18 18:34 UTC, j143 requested changes

2020-10-18 18:34 UTC, j143 commented on src/test/java/org/apache/sysds/test/functions/mlcontext/MLContextMLogregTest.java
> +		runRScript(true);
Do not run `R` script yet, first of all make sure the `dml` runs fine.

2020-10-18 18:34 UTC, j143 commented on src/test/java/org/apache/sysds/test/functions/mlcontext/MLContextMLogregTest.java
> +		TestUtils.compareMatrices(rfile, outmat, eps);
Compare the results after the `R` funtions!

2020-10-18 18:34 UTC, j143 commented on src/test/java/org/apache/sysds/test/functions/mlcontext/MLContextMLogregTest.java
> +		baseDirectory = "target/testTemp/functions/mlcontext/";
- Based on the `baseDirectory`, the `fullDMLScriptName` will be influenced.
- and input/output data will be available at `baseDirectory/in/`, `baseDirectory/out/` respectively.

2020-10-19 18:50 UTC, omkarghugarkar007 commented
Issue Solved.
1. Need to make a small change in the DML script.
2. Name of the Output variable of DMLscript and java output variable was different, thus was getting an error.

2020-10-20 05:52 UTC, j143 commented
Thank you, @omkarghugarkar007 . I will merge this after a deep pass.

---
As for the next task, have a look at https://github.com/j143/systemds/commits/GLM_MLContext 

- We will work on `GLM`
- This script is a bit tricky and long (try your best!)

2021-06-15 16:22 UTC, closed without merging